"""
This script calculate what is the proportion of gating's noise is found as noise or cluster by Chronoclust.
"""

import pandas as pd


def calculate_noise(chronoclust_result):
    """
    Calculate proportion true noise found as noise or as cluster.
    :param chronoclust_result: result file generated by chronoclust outlining the each data point's cluster assignment.
        The file must already been annotated with the label assigned by manual gating (TrueLabel) and assigned by
        mapping (PredictedLabel).
    :return: proportion of noise found and not found
    """

    df = pd.read_csv(chronoclust_result)

    true_noise_df = df[df['TrueLabel'] == 'Noise']

    true_noise_predicted_as_noise_df = true_noise_df[true_noise_df['PredictedLabel'] == 'Noise']

    true_noise_not_predicted_as_noise_df = true_noise_df[true_noise_df['PredictedLabel'] != 'Noise']

    num_noise = true_noise_df.shape[0]

    true_noise_found = true_noise_predicted_as_noise_df.shape[0] * 100 / num_noise
    true_noise_not_found = true_noise_not_predicted_as_noise_df.shape[0] * 100 / num_noise

    return true_noise_found, true_noise_not_found




